name: Rootfs
on:
  #release:
    #types: [ published ]
    workflow_dispatch:
jobs:
  rootfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-rootfs
        run: |
         sudo su
         apt update
         apt install debootstrap wget tar
         wget https://raw.githubusercontent.com/EXALAB/Anlinux-Resources/master/Scripts/Bootstrap/Debian/bootstrap.sh
         chmod +x debootstrap
         ./debootstrap aarch64 ./rootfs/debian
 
 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
         name: rootfs.tar.xz
         path: ./rootfs
