name: Rootfs
on:
  #release:
    #types: [ published ]
    workflow_dispatch:
jobs:
  rootfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-rootfs
        run: |
         sudo apt update
         sudo apt-get install qemu-user-static debian-archive-keyring debootstrap
         sudo mkdir -p ./rootfs/debian
         sudo debootstrap --arch=arm64 --foreign sid ./rootfs/debian http://deb.debian.org/debian
         cd ./rootfs/debian
         sudo tar cJf ../rootfs.tar.xz ./*
         sudo rm -rf ./*
 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
         name: rootfs.tar.xz
         path: ./rootfs/
