name: Test

on:

  #release:

    #types: [ published ]

    workflow_dispatch:

    #schedule:

    #- cron: '0 8 * * *'

jobs:

  rootfs:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: build-rootfs

        run: |

         sudo apt update

         sudo apt-get install qemu-user-static debian-archive-keyring debootstrap

         sudo mkdir -p ./debian

         sudo debootstrap --arch=arm64 --foreign sid ./debian http://deb.debian.org/debian

         cd ./debian

         sudo rm -rf debootstrap
         
         chmod 775 *

         #sudo tar cJf ../rootfs.tar.xz ./*

         #sudo rm -rf ./*

 

      - name: upload

        uses: actions/upload-artifact@v3

        with:

         name: rootfs.tar.xz

         path: ./debian
